### ISSUE TITLE
TO-DO socket events

### ISSUE THREAD

**Issue by ethanaobrien** [ethanaobrien/emuserver#4]
client => server
- [x] `disconnect-with`
- [x] `changed-uuid`
- [x] `close-entire-session`
- [x] `check-presence`
- [x] `get-remote-user-extra-data`
- [x] `set-password`

server => client
- [x] `closed-entire-session`
- [x] `userid-already-taken`
- [x] `set-isInitiator-true`
